version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
  build:
    commands:
      - echo "Build started"
      - zip -r mc-cicd-demo.zip . -x "*.git*"

artifacts:
  files:
    - mc-cicd-demo.zip
